config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "comments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @comments = Comment.order("#{sort_column} #{sort_direction}")
  end

  def new
    @comment = Comment.new
  end

  def create
    @comments = Comment.order("#{sort_column} #{sort_direction}")
    @comment = Comment.create(comment_params)
  end

  private
    def comment_params
      params.require(:comment).permit(:comment)
    end

    def sortable_columns
      ["comment", "created_at"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "comment"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def sort_link(column, title=nil)
	title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end
end

app/views/comments/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_with(model: comment, local: false) do |form| %>
    <div class="modal-body">
      <ul class="errors"></ul>
      <div class="form-group">
        <%= form.label :Add_new_comment, class:"control-label" %>
        <%= form.text_area :comment, id: :comment_comment, class: "form-control" %>
      </div>
    </div>
      <div class="modal-footer">
        <%= form.submit "Post", class: "btn btn-primary"  %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_list.html.erb
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comment %></td>
    <td><%= comment.created_at.strftime "%B %e, %Y" %></td>
  </tr>
<% end %>

app/views/comments/_new.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/_save.js.erb
$("ul.errors").html("")
<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#comment-body").html("<%= escape_javascript(render 'list') %>")
  $("#comment-form").modal("hide")
<% end %>

app/views/comments/create.js.erb
<%= render "save" %>

app/views/comments/index.html.erb
<h1>User Comments</h1>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sort_link "comment" %></th>
      <th><%= sort_link "created_at", "Added On" %></th>
    </tr>
  </thead>
  <tbody id="comment-body">
  	<%= render 'list' %>
  </tbody>
</table>
<br>

<div id="comment-form" class="modal fade"></div>
<%= link_to 'New Comment', new_comment_path, remote: true %>

app/views/comments/new.js.erb
$("#comment-form").html("<%= escape_javascript(render 'new') %>")
$("#comment-form").modal("show")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Usercomment</title>
    <%= csrf_meta_tags %>
  	<%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>